
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 18 16:39:49 CDT 2023
//----------------------------------------------------

package compiladorcpp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int P_CLOSE = 11;
  public static final int LLAVES_APER = 12;
  public static final int P_OPEN = 10;
  public static final int INT = 18;
  public static final int IGUAL = 14;
  public static final int TD_STRING = 3;
  public static final int MENORQ = 16;
  public static final int TD_INT = 2;
  public static final int PR_IF = 5;
  public static final int COMA = 9;
  public static final int MAYORQ = 15;
  public static final int FLOAT = 19;
  public static final int EOF = 0;
  public static final int CADENA_CARACT = 17;
  public static final int PR_DO = 4;
  public static final int PR_RETURN = 7;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int LLAVES_CIERR = 13;
  public static final int PUNTOYC = 8;
  public static final int PR_WHILE = 6;
}

